"""initial_schema

Revision ID: e01628c26337
Revises: 
Create Date: 2026-05-27 15:52:26.248489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e01628c26337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('group_number', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default="(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))", nullable=False),
    sa.CheckConstraint("role IN ('student', 'teacher')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('group_number', sa.Text(), nullable=False),
    sa.Column('exam_date', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='90', nullable=False),
    sa.Column('created_at', sa.Text(), server_default="(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))", nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_exams_duration_positive'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('analysis_results',
    sa.Column('result_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('normality_score', sa.Float(), nullable=False),
    sa.Column('suspicious_flags', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), server_default="(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))", nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('result_id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_analysis_results_exam_student')
    )
    op.create_table('commits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commit_id', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('exercise_id', sa.Text(), nullable=False),
    sa.Column('lines_added', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lines_removed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.CheckConstraint('lines_added >= 0', name='ck_commits_lines_added'),
    sa.CheckConstraint('lines_removed >= 0', name='ck_commits_lines_removed'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_id', 'student_id', 'file_name', name='uq_commits_commit_student_file')
    )
    op.create_table('exam_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Text(), server_default="(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))", nullable=False),
    sa.Column('ended_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_exam_sessions_exam_student')
    )
    op.create_table('similarity_pairs',
    sa.Column('pair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_a_id', sa.Integer(), nullable=False),
    sa.Column('student_b_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.Text(), server_default="(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))", nullable=False),
    sa.CheckConstraint('similarity_score >= 0', name='ck_similarity_pairs_score_positive'),
    sa.CheckConstraint('student_a_id < student_b_id', name='ck_similarity_pairs_order'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['student_a_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_b_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pair_id'),
    sa.UniqueConstraint('exam_id', 'student_a_id', 'student_b_id', name='uq_similarity_pairs_exam_a_b')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similarity_pairs')
    op.drop_table('exam_sessions')
    op.drop_table('commits')
    op.drop_table('analysis_results')
    op.drop_table('exams')
    op.drop_table('users')
    # ### end Alembic commands ###
